# Generated by Django 2.2.6 on 2019-10-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('choice1', models.CharField(max_length=150)),
                ('choice2', models.CharField(max_length=150)),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('image_url1', models.CharField(max_length=200)),
                ('image_url2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='An',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Qu')),
            ],
        ),
    ]
